# FILE: .github/workflows/main.yml

name: Build Windows Executable

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - '.github/workflows/main.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyside6==6.7.1 pyinstaller==6.8.0

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --windowed --name MultiViewBrowser main.py
          # We do NOT need to --add-data "config.json;." because our script now
          # creates the file itself in the correct location at runtime.

      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: MultiViewBrowser-Windows-Executable
          path: dist/MultiViewBrowser.exe
          if-no-files-found: error